### ISSUE TITLE
Side Effects of Your Fix to an Earlier Reported Problem (Getting Syntax Error in Browsers #7)

### ISSUE THREAD

**Issue by jmooremcc** [romanvm/kodi.web-pdb#8] opened 2018-10-26 20:32 UTC
I noticed that my RPi started freezing randomly when I wasn't debugging by Kodi addon. In the for what it's worth department, I'm using a AC WiFi dongle on my Pi to communicate wirelessly to the back end server.
The Pi would freeze and after some time it would indicate the following error: "The tuner is no longer available". I also noticed that when I rebooted, the NextPVR addon would sporadically indicate that it could not connect to the NextPVR Server. I would then do an update of the NextPVR addon and it would then connect to the server with no problem.
I wasn't sure what was causing the problem and decided to perform an experiment: I uninstalled the Wev-Pdb addon you created and then rebooted. It's now been 48 hours and I've had none of the freezing problems I was previously experiencing. My hypothesis is that your fix to the problem I had previously reported is somehow interfering with the WIFI operation. If there is some way for me to provide you more information about this issue, please let me know.

**Comment by romanvm** [comment] 2018-10-26 21:55
Web-PDB is only invoked when you explicitly call `import web_pdb; web_pdb.set_trace()` and terminated with `q` command. It does not spawn any long-running background processes on its own, unless you have left a debugging session in a suspended state without terminating it. Whatever problems you are having, they are not caused by Web-PDB.

**Comment by jmooremcc** [comment] 2018-10-27 13:39
You’re correct about web-pdb. However you said the following about the previous issue (#7):
“It is an issue with underlying asyncore-wsgi server that currently has issues with serving static files on some platforms (e.g. LibreElec on Pi).”

You created a fix for that problem which might be the source of the side effect I’m experiencing.
I’ve experienced the problem even after disabling both my addon and the web-pdb addon. Only when I uninstalled web-pdb, which I’m assuming included the fix to issue #7, did the problem go away.


John

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by romanvm** [comment] 2018-10-28 19:12
This fix was for serving file-like objects as WSGI payload and has nothing to do with your possible issues. You are barking up the wrong tree here.

**Comment by romanvm** [comment] 2018-10-30 09:52
Once again to be clear: Web-PDB is just another Python library like requests or BeautifulSoup that is executed only when called explicitly. The rest of the time it's just a bunch of files on your disk that certainly have no magic capabilities to interfere with your WiFi. I'm closing this issue as invalid.

**Closed by romanvm** 2018-10-30 09:52 UTC
Labels: invalid
